[build]
  command = "npm --prefix server ci && npm --prefix client ci && npm --prefix client run build"
  publish = "client/dist"
  functions = "server/netlify/functions"
  edge_functions = "server/netlify/edge-functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
